=== acionescu/cfg-engine/src/test/resources/test.dtd
<!ELEMENT dummy ( parent, child* )* >
<!ATTLIST dummy class NMTOKEN #IMPLIED >
<!ATTLIST dummy id NMTOKEN #IMPLIED >
<!ATTLIST dummy init-method CDATA #IMPLIED >
<!ATTLIST dummy destroy-method CDATA #IMPLIED >

<!ELEMENT dummys ( dummy* ) >

<!ELEMENT parent ( #PCDATA ) >
<!ATTLIST parent id NMTOKEN #IMPLIED >
<!ATTLIST parent id-ref NMTOKEN #IMPLIED >

<!ELEMENT child ( #PCDATA ) >
<!ATTLIST child id NMTOKEN #IMPLIED >
<!ATTLIST child id-ref NMTOKEN #IMPLIED >

=== acionescu/cfg-engine/src/test/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    cfg-engine - A Java dependency injection engine
    Copyright (C) 2009  Adrian Cristian Ionescu - https://github.com/acionescu

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<!DOCTYPE paths SYSTEM "test.dtd">

<dummys>
	<dummy id="dummy1" >
		<parent id="dummy0" />
		<child id="child1" />
		<child id="child2" />
		<child id-ref="dummy3"/>
	</dummy>
	
	<dummy id="dummy3" >
		<parent id-ref="dummy4"/>
	</dummy>
	
	<dummy id="dummy4"/>
		
</dummys>
